### PR TITLE
Debugging coverage output

### PR DESCRIPTION
**Pull request by stevepeak**

### CODE REVIEW

**Comment by stevepeak** [comment]
> extract from https://travis-ci.org/LionsAd/service_container/jobs/66540050#L1381

``` xml
<package name="Drupal\service_container\Messenger">
  <file name="/home/travis/build/LionsAd/service_container/src/Messenger/LegacyMessenger.php">
    <class name="LegacyMessenger" namespace="Drupal\service_container\Messenger">
      <metrics methods="6" coveredmethods="6" conditionals="0" coveredconditionals="0" statements="11" coveredstatements="11" elements="17" coveredelements="17"/>
    </class>
    <line num="30" type="method" name="__construct" crap="1" count="1"/>
    <line num="31" type="stmt" count="1"/>
    <line num="32" type="stmt" count="1"/>
    <line num="37" type="method" name="addMessage" crap="1" count="6"/>
    <line num="38" type="stmt" count="6"/>
    <line num="39" type="stmt" count="6"/>
    <line num="45" type="method" name="getMessages" crap="1" count="4"/>
    <line num="46" type="stmt" count="4"/>
    <line num="52" type="method" name="getMessagesByType" crap="2" count="4"/>
    <line num="53" type="stmt" count="4"/>
    <line num="54" type="stmt" count="4"/>
    <line num="60" type="method" name="deleteMessages" crap="1" count="1"/>
    <line num="61" type="stmt" count="1"/>
    <line num="62" type="stmt" count="1"/>
    <line num="68" type="method" name="deleteMessagesByType" crap="1" count="1"/>
    <line num="69" type="stmt" count="1"/>
    <line num="70" type="stmt" count="1"/>
    <line num="73" type="stmt" count="0"/>
    <metrics loc="72" ncloc="39" classes="1" methods="6" coveredmethods="6" conditionals="0" coveredconditionals="0" statements="11" coveredstatements="11" elements="17" coveredelements="17"/>
  </file>
</package>
```

## Findings
- 18 `<line>` nodes but `elements="17"`. Do you see any other inidcation that line 73 is "not real"
- `loc=72` may indicate that anything after is "not real"

**Comment by drupol** [comment]
Internet is broken today :-1:

**Comment by fabianx-ai** [comment]
Yeah, as discussed in chat, that is an xdebug_get_code_coverage() bug. I guess ignoring any lines after the num-lines-of-code is safe :).

**Comment by stevepeak** [comment]
I'm deploying a fix to our servers to check the the `metrics[loc]` and trim the reports to fix this issue.

I'll close this PR when its deployed.

**Comment by fabianx-ai** [comment]
Great, thanks! :)

**Comment by stevepeak** [comment]
Deployed :) Cheers!

**Pull request closed without merging**
