### PR TITLE
Issue #2467477 by Pol: Add check for PHP 5.3.10

### PR DESCRIPTION
**Pull request by drupol**
This module needs php 5.3.10 to work, so let's add a php restriction in the info file.

### CODE REVIEW

**Comment by dawehner** [comment]
Mh, given that we want to keep the service container compatible with Drupal core 8.0., if possible, we should rather go with PHP 5.4

@Polzme Which part of the code requires 5.5?

**Comment by drupol** [comment]
I'm unable to test with PHP 5.4 yet unfortunately.

**Comment by fabianx-ai** [comment]
For which parts do we require PHP 5.4 atm.?

I am okay to temporarily require PHP 5.4, but in the long run I still want to support PHP 5.3 using https://igor.io/2013/07/26/evolving-syntax.html to automatically convert PHP 5.4 back to 5.3.

**Comment by fabianx-ai** [comment]
We will need a test to show which core part we are using requires PHP 5.4, so we have that documented.

We also quite urgently before releasing a service_container beta should update to a newer beta of Drupal 8 Core for all code we currently have copied.

**Comment by drupol** [comment]
I'm unfortunately unable to test with PHP 5.3.

**Comment by drupol** [comment]
According to https://github.com/symfony-cmf/MediaBundle/issues/76#issuecomment-26341731, 5.3.10 is the minimum PHP version that we can use.
Updating the info file accordingly.

**Comment by fabianx-ai** [comment]
Lets get this in, 5.3.10 sounds great!

**Comment by drupol** [comment]
Yeah ! :)

 -_φol d._-

**Pull request merged**
